### ISSUE TITLE
Fields not clearing in composite tool.

### ISSUE THREAD

**Issue by simensta** [zooniverse/scribeAPI#125]
Only when you encounter two composite entries back to back.

**Comment by nonword** [comment]
oh I think I encountered this and fixed it in autocomplete work (currently in a PR). The version of the bug I saw, anyway, was due to val (the value applied to the input's value attribute) being `undefined`. When set to '' it worked. I think React skips setting attributes if the value is `undefined`.

**Comment by saschaishikawa** [comment]
yup, it's fixed. thanks
