### ISSUE TITLE
Field guide / examples

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/scribeAPI#192]
Bringing @DarrenMcRoy into this issue.

On Scribe, we have the ability to add a bit of contextual help like on https://demo-measuring-the-anzac.herokuapp.com/#/mark. We also have the ability to create additional content pages to put more complex content into. Using some combination of these two, we need to give volunteers a sufficient amount of context and assistance to be able to go through the OWW workflow.

@saschaishikawa I'm going to assume that nowhere within the content dump they gave us did they provide examples of any of the given task choices did they? If not, this is something we are going to need to bring the team onto.

@DarrenMcRoy Worth having some thoughts how the help sits between the two options we have to convey it to users. Pretty short, basic content within the "Need Some Help" button, and much longer, custom content on a "Field Guide" page.

**Comment by saschaishikawa** [comment]
@chrissnyder: other than a word document containing structured text on the kind of data they want collected?

**Comment by chrissnyder** [comment]
Yes. For example, we are asking volunteers to mark instances of sea ice thickness descriptions within the documents. Did the team point to either a document or entry that has an example of what this looks like in context?

**Comment by saschaishikawa** [comment]
No, then, I don't think we have that

**Comment by chrissnyder** [comment]
Roger that. Darren and myself will prod the team til we have something for you.

**Comment by DarrenMcRoy** [comment]
There's actually some basic stuff in the document called "OWW_Guide_Rev_2", but it's a little bit tricky to process in its current form, and it's fairly sparse. @chrissnyder -- do you have that document?

Honestly, I really love how ANZAC's "Need Some Help" pops up a box right in the window, so let's definitely do that. I assume it's the same deal.

However, I'm not sure about having what pops up be "short, basic content" -- honestly, if I'm stumped on a question, and I "need some help" with the answers, I'd like to be able to see an actual description (and, preferably, examples!) for each answer, without leaving the classifying page. (That's why the field guide on Chimp & See works so well.) Is there a way that we can do that? For instance, can what pops up from "Need Some Help" have images? Or thumbnails of examples that you could click to expand? Or could it scroll so that more stuff could fit there?

It seems to me that the ANZAC thing, for instance, asks you to choose between several types of documents, but then the "need some help" more tells you what a document is and why it's important, rather than giving any info that might help you make a correct selection. I'd like whatever pops up when you hit "need some help" to actually help you make that correct selection, yes?

**Comment by saschaishikawa** [comment]
@DarrenMcRoy: at the moment we can't include images in the "need some help" pop-ups

**Comment by simensta** [comment]
@saschaishikawa: In my help markdown files, I am able to use the image tag, but only if I place the images manually in `assets/images`. I am working on copying images into `assets/images` from help folder on `rake project_load[project]`, like we do with the background image. 

In addition to helpful modals, I am looking to create a field guide, similar to the one used in [Operation War Diary](http://www.operationwardiary.org/#/guide/cover). Would something similar be useful for OW:W?

**Comment by saschaishikawa** [comment]
@simensta: The logo SVG is also copied in like the background image. It's looking like it might be useful to have custom `assets/images` folders in each project and copy those into the app? 

The field guide modal would definitely help.
