### ISSUE TITLE
Help text for workflow questions

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/scribeAPI#233]
https://docs.google.com/document/d/1YGXQlLmp2r05i8mDmL8Hj_fm050m6-eWBZqbJB3DS40/edit?usp=sharing

Not perfect, but better than nothing. We'll iterate after the beta.

**Comment by chrissnyder** [comment]
Hold for a bit while @DarrenMcRoy makes some edits.

**Comment by DarrenMcRoy** [comment]
Give me until noon. Thanks!!

**Comment by DarrenMcRoy** [comment]
Okay, all descriptions are tweaked and beta-ready.

https://docs.google.com/document/d/1YGXQlLmp2r05i8mDmL8Hj_fm050m6-eWBZqbJB3DS40/edit#

All the "Ask a moderator" stuff on each "need some help" will be linked to a special board on Talk. (I'd prefer a button, but a hyperlink will do.)

Please also change "Pick a type of art and mark it" to "Pick a type of art and and draw a rectangle around it," for consistency; same for "Pick an event and mark it" to "Pick a type of event and and draw a rectangle around it."

**Comment by saschaishikawa** [comment]
It turns out that we can include images in the help pop-up via markdown. That said, I think the links/images in the "weather" step didn't reference anything. I've added a placeholder compass image and a link to the Beaufort scale.

The homepage looks a bit cluttered with the new content. Two solutions come to mind, 1) tweak the styling and emphasize/de-emphasize certain text relative to others (or create more of a scroll-down narrative), or 2) edit or move some of the text to the about page.

**Comment by chrissnyder** [comment]
Good stuff. Let's put the homepage design discussion in a separate issue.
