### ISSUE TITLE
Rename "bad subject"

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/scribeAPI#262]
I think "incorrect mark" or "bad mark" is a bit clearer than "bad subject."

"Subject" tends to refer to the entire page, not just a single marking on it. Thoughts?

**Comment by DarrenMcRoy** [comment]
Clarification: this should be in the transcription boxes.

For the one to mark an entire page as bad, it should be "bad page."

**Comment by nonword** [comment]
I believe this is all/partially fixed. One can now map internal terms like subject-set, subject, and group to project appropriate terms ("book", "page", "log book", etc). May need to add an extra mapping for "mark" since some projects may prefer another word (e.g. "region", "highlight"). I'll assess soon

**Comment by DarrenMcRoy** [comment]
Do we need to then manually map those terms on each of these projects (OW:W and ANZAC) ... ?

**Comment by saschaishikawa** [comment]
They just need to be defined in each project’s project.json file.

**Comment by DarrenMcRoy** [comment]
Then let's leave this open until it's done in both ANZAC and OW:W.
