### ISSUE TITLE
Feedback/issues from Kevin Wood on latest version of site

### ISSUE THREAD

**Issue by trouille** [zooniverse/scribeAPI#372]
1. The transcribe button on each mark is now missing

2. Question - I assume when there is a line break in the ms one would just use 2 or more mark boxes?

3. Question - The step "select all sea ice descriptions that apply" ---> thickness ---> heavy ice does not have a mark box option (others choices the same). This is because all the terms generated this way are associated with the page, not date, or something else?

**Comment by saschaishikawa** [comment]
1. In order to reduce clutter, we're now hiding the transcribe button unless the mark is selected. If you click on a mark that hasn't been transcribed yet, it the transcribe button should appear.

2. Not sure I understand what "ms" means. If text spans multiple lines, it makes sense to draw a box around the entire region. This will provide the transcriber with an unobstructed view of the entry.

3. Correct. These terms will be associated on a page-level; however, if it turns out to be important to know the exact location of these terms on the page, we can have users create a mark first. I would recommend against the latter this since users are already asked to mark quite a bit.
