### ISSUE TITLE
IIIF Support

### ISSUE THREAD

**Issue by hotnuts21** [zooniverse/scribeAPI#448]
HI,

Does this support loading in images through IIIF and storing the locations/markup in OpenAnnotation format?

If not, where would I start to look to modify it to at least load images via IIIF?

Thanks
Paul

**Comment by nonword** [comment]
The viewer doesn't currently exploit IIIF URIs or pull metadata. Images are loaded via whatever URLs the project creator specifies in the project CSVs.. Metadata is also derived from those CSVs. If your primary interest in supporting IIIF is for zooming/regioning, that would be a significant change to components/subject-viewer and components/subjects-zoom-pan. Integrating a smooth viewer like openseadragon would be considerably more work because the system really tightly couples the viewer and drawing tools presently.

I like the idea of supporting openannotation as an export format for consensus data, but there's no hard plan for it.

**Comment by hotnuts21** [comment]
OK thanks for the feedback. The reason for wanting to support IIIF is that our entire repository will be going that way and so it fits into our workflow.
