### ISSUE TITLE
Validation Workflows

### ISSUE THREAD

**Issue by riordan** [zooniverse/scribeAPI#90]

**Comment by chrissnyder** [comment]
To summarize from yesterday:

- The validation workflow occurs after N transcriptions occur on a secondary subjects.
- Within this workflow, a user is presented with all N transcriptions and is asked which one most closely matches the text on the subject.
- They are also presented with the ability to add an additional transcription if they feel none of the previous transcriptions match the subject. This takes them back to the transcription workflow.
- Validation is considered finished when at least Y, but not more than Z users have validated a subject. This is to allow a minimum number of validations, but stops subjects from bouncing between transcribe and validate forever.

Other points worth noting:

- The multiple transcribe and validate opinions are meant to debias user answers and attempt to provide a better quality data product.
- The number of transcriptions necessary to move a subject to validation would be configurable, down to 1 and up to whatever the project owner feels is appropriate.
- When it's set to 1, the validation workflow is reworked to a simple yes/no question for the provided transcription.

**Comment by chrissnyder** [comment]
All that said, after I've had a number of hours to think this over and I'd like to pose a few questions to the group:

- What are we going to set the default transcriptions per subject to? My instinct tells me that whatever we set this to will be the value that is used on most Scribe projects.
- What do we imagine the core audience for Scribe will be? A single curator, small scale local project? Or larger, online projects?

I ask because there feels like a tension between requiring additional transcriptions for the purposes of de-biasing, and the ability for small scale projects to get through data in a reasonable amount of time.

To really get to the heart of the matter, do we feel that any time would be saved simply choosing one of the above approaches rather than using both?
